import LegalPage from "../components/LegalPage";
export const metadata = { title: "Privacy Policy | Emryon" };
export default function PrivacyPage(){return <LegalPage title="Privacy Policy" intro="This policy explains how information is handled when you use Emryon-related pages and ProjectSupport. Emryon is Paul Wamaria's independent software and digital-product brand, not a registered company." sections={[
{title:"Information we may process",body:<><p>When you use ProjectSupport, information needed to initiate, verify, and record a contribution may be processed. This can include details you provide, transaction references, contribution amounts, payment status, and technical information needed to operate and secure the service.</p><p>Payment credentials and payment authorization are handled by the relevant payment provider. ProjectSupport does not need your M-Pesa PIN or similar secret credentials.</p></>},
{title:"How information is used",body:<p>Information is used to operate ProjectSupport, verify payment status, maintain transaction records, prevent misuse, troubleshoot the service, respond to support requests, and meet applicable legal or payment-provider requirements.</p>},
{title:"Service providers",body:<p>ProjectSupport may rely on third-party infrastructure and payment providers to host the service, process contributions, and deliver payment notifications. Those providers handle information under their own privacy terms and security practices.</p>},
{title:"Retention and security",body:<p>Reasonable steps are taken to protect information and retain it only as long as needed for operational, security, record-keeping, dispute, or legal purposes. No internet-based service can guarantee absolute security.</p>},
{title:"Contact",body:<p>For privacy questions or requests relating to ProjectSupport, contact Paul Wamaria at <a className="text-fuchsia-300 hover:underline" href="mailto:paulwamaria@gmail.com">paulwamaria@gmail.com</a>.</p>}
]}/>}
